### ISSUE TITLE
加了你的库之后报错

### ISSUE THREAD

**Issue by zengbingao** [Blincheng/Toast#1]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by Blincheng** [comment]
这应该是你的环境问题，可以尝试在Manifest.xml的application标签下添加tools:replace="android:icon, android:theme"（多个属性用,隔开，并且记住在manifest根标签上加入xmlns:tools="http://schemas.android.com/tools"
如果还是解决不了，看看官方的文档怎么说吧
http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger

如果解决了，记得告诉我你的方法哦~
