### ISSUE TITLE
我是android新手，如何重置 postdelayed 的时间

### ISSUE THREAD

**Issue by xiaogaofudao** [Blincheng/Toast#2]
给两个button 分别绑定事件。一个button 点击执行 Toast.makeText(..., '消息1', ...).show()。 另外一个 点击执行 Toast.makeText('...', '消息 2222', ....).show()。  如果我连续切换点击 按钮。 消息会来回闪动，用户体验不是很好，最好的效果是，连续执行 Toast.makeText 保留最后一次的文字并重新倒计时 关闭。不知道如何实现呢

**Comment by xiaogaofudao** [comment]
换种说法，用户其实不希望一直弹出  toast， 当前页面永远只需要一个  toast， 并且连续执行 Toast.makeText 可以重置关闭时间，而不是累加倒计时

**Comment by Blincheng** [comment]
是可以优化的点，等下今天有空我可以优化下，更新下。

**Comment by xiaogaofudao** [comment]
大神非常感谢

**Comment by Blincheng** [comment]
已经提交，v1.4版本，可以试试。

**Comment by xiaogaofudao** [comment]
嗯好的多谢了
