### ISSUE TITLE
又发现个 小问题

### ISSUE THREAD

**Issue by xiaogaofudao** [Blincheng/Toast#3]
如果两次提示 的文字长度不同。toast 的宽度不能立即 随文字长度自适应。比如第一次弹出 “客服” 这两个字。toast 比较宽度比较短， 在文字不消失的时候，立即 弹出 “客服客服客服” 这 六个字。toast 宽度会和 之前 两个字的时候一样，文字显示不全。几百毫秒后，旧toast会消失，紧接着新 toast 会恢复正常

**Comment by Blincheng** [comment]
可以了。顺便修复了一点其他的
