### ISSUE TITLE
不好意思提问题了，还有个小bug

### ISSUE THREAD

**Issue by xiaogaofudao** [Blincheng/Toast#4]
关闭通知权限。用 eToast 的时候，toast 消失后会 遗留个 空 toast 一个 小黑块

**Comment by Blincheng** [comment]
按道理是不应该的哈~我有空在统一的整理下哈，最近实在是忙

**Comment by xiaogaofudao** [comment]
多谢了哈，之前一直在做前端，最近刚学 android，麻烦你了

**Comment by Blincheng** [comment]
我看了一下。。。是我代码没提交完，不好意思了
