### ISSUE TITLE
关于 toast 被 popupwindow 覆盖问题

### ISSUE THREAD

**Issue by xiaogaofudao** [Blincheng/Toast#5]
打开通知权限，原生toast 弹出没问题可以 覆盖 popupwindow。关闭通知权限，在 popupwindow 页面里面弹出 模拟的 toast  会被 popupwindow 覆盖而 看不到。如何解决呢

**Comment by Blincheng** [comment]
对的，唯一的缺陷就是会被有些窗口覆盖，这种情况建议用其余的展示形式。然后，最近我在整理EToast2.0，会结合之前遇到的所有问题，做一个全面的兼容和协调，先凑合用下吧，再等等。

**Comment by xiaogaofudao** [comment]
大神期待 2.0 版本。说说我的想法。不论 app 通知权限是否开启，一律显示 模拟的 toast。保持各android 手机 ui 一致。toast 可以 覆盖 任何层级，且同时只能显示一个 toast。显示消失逻辑现在这个 版本的 模拟toast 就挺好的。还有就是 多次显示消失 没有内存泄露，就完美了

**Comment by Blincheng** [comment]
https://github.com/Blincheng/EToast2/tree/master
去吧~v2.0.0已经发布了，有任何问题欢迎询问，刚刚发布，难免会有问题哈
