### ISSUE TITLE
2.0 测试后 发现 android 4.4 有问题

### ISSUE THREAD

**Issue by xiaogaofudao** [Blincheng/Toast#6]
toast 可以弹出，不过toast 关闭的时候 程序崩溃，怀疑是代码调用 不支持的 api

**Comment by Blincheng** [comment]
Android5.0以下的不会有禁用系统通知权限这一说法，所以，直接会调用系统的Toast哦。

PS：并且在以下代码中直接对SDK版本号进行了判断哦~当小于19的时候会直接返回true

/**
 * 用来判断是否开启通知权限
 * */
private static boolean isNotificationEnabled(Context context){
    if(android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.KITKAT){
        return true;
    }


________________________________
发件人: John Gao <notifications@github.com>
发送时间: 2017年6月30日 10:46
收件人: Blincheng/Toast
抄送: Subscribed
主题: [Blincheng/Toast] 2.0 测试后 发现 android 4.4 有问题 (#6)


toast 可以弹出，不过toast 关闭的时候 程序崩溃，怀疑是代码调用 不支持的 api

―

**Comment by xiaogaofudao** [comment]
4.4 在设置的程序列表里打开，里面有个 checkbox 显示通知。勾掉也相当于 屏蔽通知了
![tim 20170703093411](https://user-images.githubusercontent.com/9261849/27775251-f1046a98-5fd2-11e7-8abd-77240e7f7fc3.png)
4.4 toast 弹出正常，关闭的时候 程序会崩溃。不知道什么原因
![image](https://user-images.githubusercontent.com/9261849/27775268-188f08f2-5fd3-11e7-906b-690ba870cb22.png)

**Comment by Blincheng** [comment]
我没看错的话，你这个模拟器的标题是API_19:5554 难道不是API 19，不是Android5.0吗？具体有错误日志可以给我看下吗？我这边不能重现

________________________________
发件人: John Gao <notifications@github.com>
发送时间: 2017年7月3日 1:36
收件人: Blincheng/Toast
抄送: Blincheng; Comment
主题: Re: [Blincheng/Toast] 2.0 测试后 发现 android 4.4 有问题 (#6)


4.4 在设置的程序列表里打开，里面有个 checkbox 显示通知。勾掉也相当于 屏蔽通知了
[tim 20170703093411]<https://user-images.githubusercontent.com/9261849/27775251-f1046a98-5fd2-11e7-8abd-77240e7f7fc3.png>

[https://user-images.githubusercontent.com/9261849/27775251-f1046a98-5fd2-11e7-8abd-77240e7f7fc3.png]

4.4 toast 弹出正常，关闭的时候 程序会崩溃。不知道什么原因
[image]<https://user-images.githubusercontent.com/9261849/27775268-188f08f2-5fd3-11e7-906b-690ba870cb22.png>

[https://user-images.githubusercontent.com/9261849/27775268-188f08f2-5fd3-11e7-906b-690ba870cb22.png]

―

**Comment by xiaogaofudao** [comment]
经测试。4.4 app 勾掉 show notifications 选项。toast 关闭消失的时候会 崩溃。我新建了个 空项目测试的
![image](https://user-images.githubusercontent.com/9261849/27776593-9b13d9c8-5fde-11e7-8d13-099c02ef6cf5.png)
![image](https://user-images.githubusercontent.com/9261849/27776605-bddb43b0-5fde-11e7-8473-d9b2db655c1e.png)

**Comment by Blincheng** [comment]
首先你确定你的模拟器是Android4.4哈~因为我看你的截图是Android5.0
然后根据你提出的意见，由于在Android5.0以下无法获取是否打开系统通知权限，所以为了防止用户看不到Toast，最终的逻辑优化了一下：
1.当用户是5.0以下的机器时，永远只显示EToast
2.当用户是5.0以上的机器是，如果打开了通知权限，则显示系统Toast；反之则显示Etoast

**Comment by Blincheng** [comment]
然后你更新下版本到V2.0.1

**Comment by xiaogaofudao** [comment]
确定是  4.4 
![tim 20170703114317](https://user-images.githubusercontent.com/9261849/27777369-d73e1e26-5fe4-11e7-95e9-bc987dae6003.png)
更新 2.0.1 后经测试没有崩溃现象。太感谢了

**Comment by Blincheng** [comment]
嗯，最新博文已经更新，欢迎支持~
http://blog.csdn.net/qq_25867141/article/details/74194503
